spring.application.name=notificaciones_service

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

twilio.account_sid=${TWILIO_ACCOUNT_SID}
twilio.auth_token=${TWILIO_AUTH_TOKEN}
twilio.phone_number=${TWILIO_PHONE_NUMBER}

security.jwt.secret=proyecto_pragma_plazoleta_firma_token_seguro_2026
server.port=8083
